### ISSUE TITLE
Submenú para ediciones anteriores

### ISSUE THREAD

**Issue by ldubiau** [lasdesistemas/lds#15]
En el menu de la home de LDS > FEMIT , se podrá tener un sub-menú para ediciones anteriores?

**Comment by daquiroz** [comment]
Me parece que pueden ser demasiados niveles/clicks para verlo. Ahora lo dejé dividido en el menu, qué te parece así?

**Comment by ldubiau** [comment]
me parece bien, Dani! gracias!
