### ISSUE TITLE
Fix favicon

### ISSUE THREAD

**Issue by ldubiau** [lasdesistemas/lds#20]

**Comment by vnbarr** [comment]
Comparto los archivos que nos envió Denise!

![mstile-150x150](https://user-images.githubusercontent.com/13315747/86501902-d6272600-bd73-11ea-9fba-9d901a156d88.png)
![favicon-32x32](https://user-images.githubusercontent.com/13315747/86501903-d7585300-bd73-11ea-90d0-e3aad4abf939.png)
![favicon-16x16](https://user-images.githubusercontent.com/13315747/86501906-d7f0e980-bd73-11ea-8247-365e3619de88.png)
![apple-touch-icon](https://user-images.githubusercontent.com/13315747/86501908-d7f0e980-bd73-11ea-92fa-9012ee6cf7bf.png)
![android-chrome-512x512](https://user-images.githubusercontent.com/13315747/86501909-d8898000-bd73-11ea-85be-70d44c7ff9d4.png)
![android-chrome-192x192](https://user-images.githubusercontent.com/13315747/86501910-d9221680-bd73-11ea-941a-0f21c7efc9fd.png)
