### ISSUE TITLE
¿Está ok que el header no cubra el ancho de la pantalla como el footer?

### ISSUE THREAD

**Issue by naysolange** [lasdesistemas/lds#8]
No recuerdo bien como estaba en el diseño, pero visualmente me hace ruido que el header sea chico y no llegue a los extremos de la pantalla como el footer. Así lo veo en firefox:

![Screenshot_2020-05-12 FEMIT 2020 - Las de Sistemas](https://user-images.githubusercontent.com/8364586/81732969-a8a2b800-9467-11ea-9fe1-31a4e9cddaf2.png)

**Comment by ldubiau** [comment]
@nportas está duplicado este issue

**Comment by naysolange** [comment]
justo me di cuenta q lo habias subido, lo cierro
